static_resources:
  listeners:
  - name: listener_https
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: https_ingress
          use_remote_address: true
          stream_idle_timeout: 0s
          upgrade_configs:
          - upgrade_type: websocket
          route_config:
            name: local_route
            virtual_hosts:
            - name: agave
              domains: ["*"]
              routes:
              - name: health
                match:
                  path: "/health"
                route:
                  cluster: agave_rpc
                  timeout: 5s
                response_headers_to_add:
                - header:
                    key: Cache-Control
                    value: public, max-age=5
                  append: false
              - name: websocket_upgrade
                match:
                  prefix: "/"
                  headers:
                  - name: upgrade
                    exact_match: websocket
                route:
                  cluster: agave_ws
                  timeout: 0s
                  idle_timeout: 0s
              - name: default_rpc
                match:
                  prefix: "/"
                route:
                  cluster: agave_rpc
                  timeout: 300s
                  retry_policy:
                    retry_on: 5xx
                    num_retries: 3
                    per_try_timeout: 30s
                    retry_back_off:
                      base_interval: 30s
                      max_interval: 30s
          http_filters:
          - name: envoy.filters.http.cache
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.http.cache.simple_http_cache.v3.SimpleHttpCacheConfig
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              log_format:
                text_format: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(:PATH)%\" %RESPONSE_CODE% ms D:%DURATION% ms\n"
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: /etc/envoy/tls/origin.cert.pem
              private_key:
                filename: /etc/envoy/tls/origin.key

  - name: listener_http
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: http_ingress
          route_config:
            name: http_redirect
            virtual_hosts:
            - name: redirect
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                redirect:
                  https_redirect: true
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: agave_rpc
    connect_timeout: 10s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: agave_rpc
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: agave-rpc
                port_value: 8899
    dns_lookup_family: V4_ONLY
    common_http_protocol_options:
      idle_timeout: 60s
    health_checks:
    - timeout: 2s
      interval: 5s
      unhealthy_threshold: 3
      healthy_threshold: 2
      http_health_check:
        path: /health
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http_protocol_options: {}

  - name: agave_ws
    connect_timeout: 5s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: agave_ws
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: agave-rpc
                port_value: 8900
    dns_lookup_family: V4_ONLY
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http_protocol_options: {}

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

